name: Build and Test

on:
  push:
    branches:
      - main
      - gh-pages

jobs:
  build:
    runs-on: beevelop/cordova
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Custom Build Script
        run:  /bin/bash -c "cd /root/shared-volume/MyApp/ && yes n | cordova run android && send "n\r" && touch hello"
