name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Execute Custom Build Script
        run: 
          chmod +x ./script.sh
          ./script.sh        # Execute the script
